version: "3.8"

services:
  backend:
    build:
      context: ./Jeonse-ive-BE
    container_name: jeons-ive-spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

  frontend:
    build:
      context: ./Jeonse-ive-FE
    container_name: realty-react-app
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    volumes:
      - ./Jeonse-ive-FE:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    networks:
      - backend

  db:
    image: postgres:15
    container_name: jeonse-ive-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jeonse-ive
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
